### ISSUE TITLE
Can't install pod because of conflicting names

### ISSUE THREAD

**Issue by respan** [rainbean/TensorflowPod#5]
Hello. Thanks for your work, but i have problem with installing and using this pod.

I'm using Firebase, and it comes with Protobuf pod. And looks like it's colliding with libprotobuf.a you use in your podspec directly on `pod install`:

`[!] The 'Pods-Example' target has libraries with conflicting names: libprotobuf.a.`

Any ideas for what can i do? I tried to fork TensorflowPod and delete libprotobuf.a from podspec, it helped with `pod install`, but i've got more than 40 errors on linking stage.

**Comment by rainbean** [comment]
@respan This project aims for iOS cocoapod integration with TensorFlow (Objective-C, Swift). Better not expect to be compatible with other programming platform(s), such as Firebase. 

The only suggestion, off top of my head, is to build TensorFlow from scratch, following README procedure.  Yet I am not aware of readiness of TensorFlow on Firebase platform, good luck and take your own risk.
